# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52182680500d9b6a9614f4bd2620a7d81c9b7abde426016fbf0f953efb5f5e62baf1e3006c67d72c5b321aee4910390d97855ee5fab4701cb00c5dfaf0b620ae
  facebook_app_id: <%= ENV["FACEBOOK_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>


test:
  secret_key_base: b7856b8ea43865fafbe64259860969b5b8f7168b5446c2f4e2c3f1d2ee2a4f0b2fc64917a35b1f5f4865e0d294f8f609831f56f8408cbaf3e29f730e254e4cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  facebook_app_id: <%= ENV["FACEBOOK_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
